### PR TITLE
Add web server's hostname and local ip address

### PR DESCRIPTION
**Pull request by ntoreg**
#### What's this PR do?
Show web server's hostname and local ip address in html.

#### Any background context you want to provide?
I would like to check these attributes, when web servers behind a load balancer. 

#### Screenshots
**lang_ja**
env

**lang_en**
env-man

### CODE REVIEW

**Comment by dounokouno** [comment]
Thank you PR. I will check.

**Comment by dounokouno** [comment]
@ntoreg Merge PR. I did a little fix. Please check it. https://github.com/dounokouno/ENV-Man/commit/509ce419f7f3dcac774c7240ef3f1785d3ce2187

**Comment by ntoreg** [comment]
@dounokouno Thank you for your fixes. It's so good!

**Comment by dounokouno** [comment]
Thank you :smile:

**Pull request merged**
